{% set name = "taxcalc" %}
{% set version = "6.2.0" %}
{% set python_min = "3.11" %}
{% set python_max = "3.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PSLmodels/Tax-Calculator/archive/{{ version }}.tar.gz
  sha256: 2e115548269313f330cd2a69dc86be45163f6279a54e64776f143f9abe8be392

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tc = taxcalc.cli.tc:cli_tc_main

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }},<{{ python_max }}
    - numpy >=1.26
    - pandas >=2.2
    - bokeh >=2.4
    - requests
    - numba
    - paramtools >=0.20.0
    - aiohttp
    - setuptools

test:
  imports:
    - taxcalc
  commands:
    - tc --help
    - tc --test

about:
  home: https://github.com/PSLmodels/Tax-Calculator
  license: CC0-1.0
  license_family: PUBLIC-DOMAIN
  license_file: docs/about/LICENSE.md
  summary: open-source microsimulation model for static analysis of USA federal income and payroll taxes.
  description: Tax-Calculator is an open-source microsimulation model for static analysis of USA federal income and payroll taxes.
  doc_url: http://taxcalc.pslmodels.org
  dev_url: https://github.com/PSLmodels/Tax-Calculator

extra:
  recipe-maintainers:
    - MattHJensen
    - jdebacker
